#########################################
################# Notes #################
#########################################

############################################################################
# This is the default configuration file. Adjust the settings if you want. #
############################################################################

### Blocked blocks ###
block-tnt: true
block-water: false
block-lava: true
block-monsterspawner: false
block-endportalframe: false

### Actions ###
###### Which actions should occur when someone tries to place a blocked block? ######
warn-console: true
warn-ops: true
warn-permissions: false